server:
  port: 8081

spring:
  application:
    name: ACCOUNT-SERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopping?currentSchema=account_service}
    username: ${SPRING_DATASOURCE_USERNAME:shopping}
    password: ${SPRING_DATASOURCE_PASSWORD:shopping}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
