server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
    prefer-ip-address: false
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

auth:
  jwt:
    secret: ${JWT_SECRET:UnI6T1JQdWdJYW1lcDJjdmlOTThMc0ZpbDJwY3N3SFJ6aEhTS2FKQ3BaYz0=}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
